type Hooter {
  _id: ID
  user_name: String!
  display_name: String!
  joinedAt: String!
  bornAt: String
  bio: String
  profile_picture_uri: String
  profile_banner_uri: String
  location: String
  hoots: [Hoot]
  listeners: [Noter]
}

type Noter {
  _id: ID
  display_name: String
  scketuser_name: String
  profile_picture_uri: String
  listeners_num: Float
}

type Hoot {
  _id: ID
  hooter: Noter
  hoot: String
  createdAt: 
}

type Query {
  user: 
}
